version: '3.8'

services:

    php:
        build:
            context: './.docker/php'
            dockerfile: 'Dockerfile'
            args:
                uid: '1000'
                user: 'app'
        user: '1000'
        working_dir: '/app'
        tty: true
        stdin_open: true
        volumes:
            - './:/app'
